import React from "react";

const Icon = () => null;

export const FaArrowLeft = Icon;
export const FaBars = Icon;
export const FaBell = Icon;
export const FaBolt = Icon;
export const FaBriefcase = Icon;
export const FaCalendarAlt = Icon;
export const FaChartLine = Icon;
export const FaCheckCircle = Icon;
export const FaChevronDown = Icon;
export const FaChevronRight = Icon;
export const FaChevronUp = Icon;
export const FaCircle = Icon;
export const FaClock = Icon;
export const FaCode = Icon;
export const FaCog = Icon;
export const FaComment = Icon;
export const FaDownload = Icon;
export const FaEdit = Icon;
export const FaExclamationTriangle = Icon;
export const FaFileAlt = Icon;
export const FaFileImage = Icon;
export const FaFilePdf = Icon;
export const FaFolderOpen = Icon;
export const FaGithub = Icon;
export const FaGoogle = Icon;
export const FaHistory = Icon;
export const FaHome = Icon;
export const FaLock = Icon;
export const FaMagic = Icon;
export const FaPaperclip = Icon;
export const FaPaperPlane = Icon;
export const FaPlus = Icon;
export const FaRegCopy = Icon;
export const FaRegKeyboard = Icon;
export const FaRobot = Icon;
export const FaRocket = Icon;
export const FaSave = Icon;
export const FaSearch = Icon;
export const FaSignOutAlt = Icon;
export const FaStickyNote = Icon;
export const FaTasks = Icon;
export const FaTimes = Icon;
export const FaTrash = Icon;
export const FaUserCircle = Icon;
export const FaUserPlus = Icon;
export const FaUsers = Icon;

